version: '3'
services:
  rag-backend:
    env_file:
      - rag_chatbot_backend/keys.env
    build:
      context: ./rag_chatbot_backend
      dockerfile: Dockerfile
    volumes:
      - Data:/Data
    restart: unless-stopped
    networks:
      - caddy-vps
  chroma:
    image: chromadb/chroma
    env_file:
      - chroma/chroma.env
    volumes:
      - Data:/chroma/chroma
    restart: unless-stopped
    networks:
      - caddy-vps  
  rag-frontend:
    build:
      context: ./rag_chatbot_frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - caddy-vps

networks:
  caddy-vps:
    external: true

volumes:
  Data:
    driver: local
