version: '3'
services:
  rag-backend:
    env_file:
      - rag_chatbot_backend/keys.env
    build:
      context: ./rag_chatbot_backend
      dockerfile: Dockerfile
    volumes:
      - Data:/Data
    restart: unless-stopped
  chroma:
    image: chromadb/chroma
    env_file:
      - chroma/chroma.env
    volumes:
      - Data:/chroma/chroma
    restart: unless-stopped
  rag-frontend:
    build:
      context: ./rag_chatbot_frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config


volumes:
  Data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
