version: '3'
services:
  rag-backend:
    env_file:
      - rag_chatbot_backend/keys.env
    build:
      context: ./rag_chatbot_backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - $PWD/Data/backend_data:/Data
    restart: unless-stopped
  rag-chroma:
    image: chromadb/chroma
    env_file:
      - chroma/chroma.env
    ports:
      - 8000:8000
    volumes:
      - $PWD/Data/chroma_data:/chroma/chroma
    restart: unless-stopped
  # rag-frontend:
  #   build:
  #     context: ./rag_chatbot_frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped
